# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command - inject noscript content and build assets
  command = "npm run build"

  # Publish directory
  publish = "."

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects and rewrites
# Ensure clean URLs work
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# SPA fallback for client-side routing (if needed)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
